// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0XQO5hCpPiEcQ5xfzRrxZm21kQMh8nR4',
    appId: '1:1034615009491:web:97ba7990d883fe980a2426',
    messagingSenderId: '1034615009491',
    projectId: 'chatbuddy-9d4f4',
    authDomain: 'chatbuddy-9d4f4.firebaseapp.com',
    databaseURL: 'https://chatbuddy-9d4f4-default-rtdb.firebaseio.com',
    storageBucket: 'chatbuddy-9d4f4.appspot.com',
    measurementId: 'G-DJJ6KSSLNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9zQXlPFGkinWqJP40qp4wRv8vke187o',
    appId: '1:1034615009491:android:316fa3211c271c5d0a2426',
    messagingSenderId: '1034615009491',
    projectId: 'chatbuddy-9d4f4',
    databaseURL: 'https://chatbuddy-9d4f4-default-rtdb.firebaseio.com',
    storageBucket: 'chatbuddy-9d4f4.appspot.com',
  );
}
